spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autolabel?useUnicode=true&useSSL=true&characterEncoding=utf8
    username: root
    password: 84769629a
    hikari:
      max-lifetime: 120000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决Failed to start bean ‘documentationPluginsBootstrapper问题
server:

  port: 8000

############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token?? (????cookie??)
  token-name: satoken
  # token??????s ??30?, -1??????
  timeout: 2592000
  # token????? (???????????token??) ??: ?
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: false
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: true
  # token??
  token-style: uuid
  # ????????
  is-log: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #  mybatis-plus日志
